Added a function to check for package manager locks
rackerlabs/auter pull request #102
Opened 2018-02-07 12:47 UTC by reaperzn

2018-02-07 12:49 UTC, reaperzn commented
This is a possible fix for #101

2018-02-13 18:16 UTC, Pingue requested changes

2018-02-13 18:16 UTC, Pingue commented on auter.yumdnfModule
> +        logit "Final attemt to wait for yum to release lock file failed. Aborting auter run"
Spelling

2018-02-14 13:14 UTC, Pingue approved these changes

2018-02-14 15:29 UTC, Pingue requested changes
I've tested on CentOS 6.9, without problems - I'll do some more testing on other OS.

2018-02-14 15:29 UTC, Pingue commented on auter.yumdnfModule
> +        logit "Final attempt to wait for yum to release lock file failed. Aborting auter run"
Should this start with "INFO:" for consistency?

2018-02-14 15:29 UTC, Pingue commented on auter.yumdnfModule
> +      [[ ! -f /var/run/yum.pid ]] && logit "yum lock has been released" && break
As above - should this start with INFO?

2018-02-20 17:00 UTC, Pingue approved these changes

2018-03-02 13:03 UTC, Pingue commented
Tested and working on RHEL6 and RHEL7. Apt has the framework, but is not implemented, same for DNF, however this doesn't make any changes to these systems. Merging this for now, DNF and apt will need to be added later.

2018-03-02 13:03 UTC, merged