Feature/log auter prep when no update
rackerlabs/auter pull request #139
Opened 2018-04-10 17:36 UTC by nickrhodes-gh

For rackerlabs/auter/issues/133.

Always log the prep output regardless of whether there were any package updates. This PR also add a date stamp to the top of the file to make it clear which prep/apply the output file is for.

2018-04-30 12:11 UTC, reaperzn requested changes

2018-04-30 12:11 UTC, reaperzn commented on auter.yumdnfModule
> +  local -i RC
For consistency, these should be declared using ```declare -i -l```

2018-04-30 12:11 UTC, reaperzn commented on auter.yumdnfModule
> +    PREPOUTPUT+=$("${PACKAGE_MANAGER}" "${PACKAGEMANAGEROPTIONS[@]}" check-update 2>&1)
In line 72 you encapsulated the declaration with quotes, you should do the same here

2018-04-30 12:11 UTC, reaperzn commented on auter.yumdnfModule
> +  local TRANSACTIONID
These are not entirely required but declaring them here does make it much easier to see what variables are being used in the function so I am ok with that however as mentioned in a previous comment, For consistency, these should be declared using ```declare -l```

2018-04-30 18:51 UTC, nickrhodes-gh commented
Updated with the review suggestions.

2018-05-04 15:50 UTC, reaperzn approved these changes

2018-05-04 15:50 UTC, merged