Corrected issues from #151 and fixed shellcheck problems
rackerlabs/auter pull request #153
Opened 2018-05-17 15:02 UTC by reaperzn

2018-05-17 16:08 UTC, reaperzn commented
Resolves #151

2018-05-19 10:34 UTC, rhodesn requested changes

2018-05-19 10:34 UTC, nickrhodes-gh commented on auter.aptModule
> +            DOWNLOADOPTION=("-o dir::cache::archives=${DOWNLOADDIR}/${CONFIGSET}")
This needs to be:
```sh
DOWNLOADOPTION=("-o" "dir::cache::archives=${DOWNLOADDIR}/${CONFIGSET}")
```
To separate the two into individual array indexes. If we don't do this then apt will download updates to `/var/cache/apt/archives` instead.

2018-05-19 10:41 UTC, nickrhodes-gh commented on auter.aptModule
> +      RUN_OUTPUT=$("${PACKAGE_MANAGER}" "${UPDATEACTION}" "${PACKAGEMANAGEROPTIONS[@]}" -y "${DEBS}")
Need to unquote "${DEBS}" as it's returning:
```sh
E: Unsupported file /var/cache/auter/default/*.deb given on commandline
```

2018-05-21 16:58 UTC, rhodesn approved these changes

2018-05-21 17:19 UTC, nickrhodes-gh commented
Tested the changes and it all looks good.

2018-05-21 17:19 UTC, merged