Make post-reboot script delay configurable
rackerlabs/auter pull request #205
Opened 2018-12-19 10:59 UTC by nrhodes91

During testing, and other times, it is useful to set a delay shorter
than the currently hardcoded 5 minutes.

It's not documented in auter.conf, however it should be pretty clear to
anyone able to read the auter script that it can be overridden in
auter.conf.

2018-12-19 11:56 UTC, reaperzn requested changes
Hey @nrhodes91,

The reason for this delay was that there are often startup processes which either start after the scheduled cron `@reboot` job or are still in running the startup process when that schedule is hit. The purpose of this delay was to make an attempt at ensuring the post-reboot execution is the last thing that is run after all other startup processes have been run. 

I agree that this may be useful to override for testing and build purposes but in production I am not too sure its the greatest idea. What we may consider doing is allowing it to be configurable with a minimum time of say 2 mins but still leave the default (and recommendation) to 5 minutes.

If we are going to allow this to be overridden then we need to also add some integrity checks to ensure they are within a reasonable range of values. So my recommendation would be that if the value is less that 120 or greater than 1800 then we set the default value of 300

Overall there is nothing wrong with the existing changes proposed however we do introduce a possible user definition which should be validated.

2018-12-19 11:56 UTC, reaperzn commented on auter
> +  tty -s || sleep ${POSTREBOOTDELAY}
Maybe we add some validation here:
```
([[ ${POSTREBOOTDELAY} -lt 120 ]] || [[ ${POSTREBOOTDELAY} -gt 1800 ]]) && ${POSTREBOOTDELAY}=300
tty -s || sleep ${POSTREBOOTDELAY}
```

2018-12-19 12:46 UTC, nrhodes91 commented
I'd argue that it's on the user to validate their requirements correctly, just as with Apache MaxRequestWorkers and MySQL innodb_buffer_pool_size. Silently overriding user configuration will also cause some confusion.

2018-12-26 16:54 UTC, reaperzn commented
@nrhodes91 Sorry, I just saw this now, So you are correct in that we should not be adjusting values silently, we should definitely add a message to the check. possibly something like:
```
if ([[ ${POSTREBOOTDELAY} -lt 120 ]] || [[ ${POSTREBOOTDELAY} -gt 1800 ]]); then
  ${POSTREBOOTDELAY}=300
  logit "WARNING: POSTREBOOTDELAY value (${POSTREBOOTDELAY}) set out of range (<120 or >1800). Using the default value of 300"
fi 
tty -s || sleep ${POSTREBOOTDELAY}
```

If we are going to expect the user to validate this themselves then we should at least add documentation around the potential impacts of setting this value too high or too low, keeping in mind that some users may easily overlook (as we initially did) some of the considerations that led us to implementing this delay in the first place.

2019-01-12 16:02 UTC, closed without merging