Added rotate function for last output files in /var/lib/auter
rackerlabs/auter pull request #94
Opened 2018-02-01 16:20 UTC by reaperzn

2018-02-01 16:32 UTC, reaperzn commented
This addresses #89

2018-02-15 03:00 UTC, Beerey commented
Is there any reason to have this functionality in auter instead of just writing a logrotate config?

2018-02-16 10:49 UTC, reaperzn commented
@Beerey logrotate was an option however due to the nature of auter, we will only be rotating these files at execution time. This does not require rotating on a schedule. There is also the possibility that auter may be run multiple times on the same day as part of troubleshooting efforts, this is one of the main purposes of these files. Note that this is not a conventional log file, it is a capture of stdout and stderr from specific yum commands. Auter does not appended to this file, it is overwritten every execution. 

We could use logrotate however we would need to ensure that we use the --force option. I am not entirely opposed to the option of using logrotate aside from the fact it adds an additional dependency and it is easy enough to handle within the code. 

Is there any major concern for having this functionality within the auter code?

2018-03-06 18:31 UTC, Pingue requested changes
Only minor name changes causing problems thanks to my OCD - I'll give it another test once done!

Cheers

2018-03-06 18:31 UTC, Pingue commented on auter.aptModule
>    [[ "${PREPOUTPUT}" ]] && echo "${PREPOUTPUT}" > ${DATADIR}/last-prep-${CONFIGSET}
As discussed, this should be last-prep-output-${....

2018-03-06 18:31 UTC, Pingue commented on auter.yumdnfModule
> +  [[ "${PREPOUTPUT}" ]] && echo "${PREPOUTPUT}" > ${DATADIR}/last-prep-${CONFIGSET}
As discussed, this should be last-prep-output-${....

2018-03-07 11:30 UTC, popindavibe commented on auter
> +  [[ -e "${OUTPUT_FILE}.${ROTATE}" ]] && rm -f "${OUTPUT_FILE}.${ROTATE}"
It could be relevant to include all files numbered above ROTATE, to avoid left-overs when modifying the value. 
Ex:
```
if [[ -e "${OUTPUT_FILE}.${ROTATE}" ]]; then
  ROTATE_MAX_FOUND=$(ls -1 ${OUTPUT_FILE}.* | tail -n 1 | sed 's/.*\([0-9]\{1,\}\)$/\1/' )
  for i in `seq ${ROTATE} 1 ${ROTATE_MAX_COUNT}`; do
    [[ -e  "${OUTPUT_FILE}.$i" ]] && rm -f "${OUTPUT_FILE}.$i"
  done
fi
```

2018-03-07 15:00 UTC, Pingue approved these changes

2018-03-07 15:01 UTC, Pingue commented on auter
> +  [[ -e "${OUTPUT_FILE}.${ROTATE}" ]] && rm -f "${OUTPUT_FILE}.${ROTATE}"
Agreed - I'll raise this as a separate issue :)

2018-03-07 15:01 UTC, merged